# Constant temperature - R0 data 
# From Mordecai et al 2019

AeaeDENV_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AeaeDENV.R0.csv"))
AeaeZIKV_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AeaeZIKV.R0.csv"))
AealDENV_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AealDENV.R0.csv"))
AetaRVFV_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AetaRVFV.R0.csv"))
AetaSINV_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AetaSINV.R0.csv"))
AetrEEEV_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AetrEEEV.R0.csv"))
AngaPfal_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AngaPfal.R0.csv"))
CxanMVEx_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxanMVEx.R0.csv"))
CxanRRVx_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxanRRVx.R0.csv"))
CxpiSINV_R0  <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxpiSINV.R0.csv"))
CxpiWNVxl_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxpiWNVx.R0.csv"))
CxtaWEEV_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxtaWEEV.R0.csv"))
CxtaWNVx_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxtaWNVx.R0.csv"))
CxunWNVx_R0 <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxunWNVx.R0.csv"))

usethis::use_data(AeaeDENV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(AeaeZIKV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(AealDENV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(AetaRVFV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(AetaSINV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(AetaEEEV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(AngaPfal_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(CxanMVEx_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(CxanRRVx_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(CxpiSINV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(CxpiWNVxl_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(CxtaWEEV_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(CxtaWNVx_R0,  compress = "xz", overwrite = TRUE)
usethis::use_data(CxunWNVx_R0,  compress = "xz", overwrite = TRUE)

AeaeDENV_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AeaeDENV.T.csv"))
AeaeZIKV_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AeaeZIKV.T.csv"))
AealDENV_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AealDENV.T.csv"))
AetaRVFV_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AetaRVFV.T.csv"))
AetaSINV_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AetaSINV.T.csv"))
AetrEEEV_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AetrEEEV.T.csv"))
AngaPfal_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "AngaPfal.T.csv"))
CxanMVEx_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxanMVEV.T.csv"))
CxanRRVx_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxanRRVx.T.csv"))
CxpiSINV_T  <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxpiSINV.T.csv"))
CxpiWNVxl_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxpiWNVx.T.csv"))
CxtaWEEV_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxtaWEEV.T.csv"))
CxtaWNVx_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxtaWNVx.T.csv"))
CxunWNVx_T <- read.csv(here("data-raw", "Thermal-Eco-MBD-main", "CxunWNVx.T.csv"))

usethis::use_data(AeaeDENV_T, overwrite = TRUE)
usethis::use_data(AeaeZIKV_T, overwrite = TRUE)
usethis::use_data(AealDENV_T, overwrite = TRUE)
usethis::use_data(AetaRVFV_T, overwrite = TRUE)
usethis::use_data(AetaSINV_T, overwrite = TRUE)
usethis::use_data(AetaEEEV_T, overwrite = TRUE)
usethis::use_data(AngaPfal_T, overwrite = TRUE)
usethis::use_data(CxanMVEx_T, overwrite = TRUE)
usethis::use_data(CxanRRVx_T, overwrite = TRUE)
usethis::use_data(CxpiSINV_T, overwrite = TRUE)
usethis::use_data(CxpiWNVxl_T, overwrite = TRUE)
usethis::use_data(CxtaWEEV_T, overwrite = TRUE)
usethis::use_data(CxtaWNVx_T, overwrite = TRUE)
usethis::use_data(CxunWNVx_T, overwrite = TRUE)

vector_reference <- read.csv(here("data-raw", "vector-pathogen_reference.csv"))

usethis::use_data(vector_reference, internal = TRUE, overwrite = TRUE, compress = "bzip2")

